Repository googleapis/nodejs-retail, pull requests merged in 2021-02, with the labels that each got.

#8 chore: update CODEOWNERS config
  .github/CODEOWNERS
Labels: automerge, cla: yes, cla: yes

#7 build: migrate to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
Labels: automerge, cla: yes, cla: yes

#14 chore: update package name, build config, protos
  .jsdoc.js
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  linkinator.config.json
  protos/google/cloud/retail/v2/import_config.proto
  protos/google/cloud/retail/v2/product.proto
  protos/google/cloud/retail/v2/product_service.proto
  protos/google/cloud/retail/v2/user_event_service.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v2/gapic_metadata.json
  src/v2/product_service_client.ts
  src/v2/user_event_service_client.ts
  src/v2alpha/gapic_metadata.json
  src/v2beta/gapic_metadata.json
  synth.metadata
Labels: cla: yes, cla: yes, context: partial

#16 refactor(nodejs): move build cop to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: cla: yes, cla: yes, context: full
