Repository googleapis/nodejs-retail, pull requests merged in 2021-03, with the labels that each got.

#18 feat(docs): promote to ga
  .repo-metadata.json
  README.md
  synth.metadata
Labels: api: retail, cla: yes, cla: yes

#20 build: update gapic-generator-typescript to v1.2.10.
  synth.metadata
  webpack.config.js
Labels: api: retail, automerge, cla: yes, cla: yes, context: full

#21 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .repo-metadata.json
  synth.metadata
  synth.py
Labels: api: retail, cla: yes
